### ISSUE TITLE
unable to build default example image

### ISSUE THREAD

**Issue by parubets** [astro/nix-openwrt-imagebuilder#10]
Hello!

I'm trying to build custom image for `glinet_gl-ar750s` profile router. it also has`nand` variant instead of `generic` so I manually adjusted this value in `builder.nix` and in `files.nix`

Using all this adjustments build gives me:
```
nix run .#example-image
error: No match for OpenWRT profile glinet_gl-ar750s
```

Then i decided to build just pure example image, and I got:
```
$ nix run .#example-image
error: unable to execute '/nix/store/yxl6dhv5w1r4nxyvndvv1r7s3m4gxk79-openwrt-21.02.3-nix-lantiq-xrx200-avm_fritz7412/bin/openwrt': No such file or directory
```

I'm starting to suspect that images should be build on the router itself... or am I doing something wrong? Please help :)

**Comment by astro** [comment]
Use `nix build -vL .#profiles-list` to see what profiles are available. There are three with similar names:
- `glinet_gl-ar750`
- `glinet_gl-ar750s-nor`
- `glinet_gl-ar750s-nor-nand`
