### ISSUE TITLE
Build images from snapshot

### ISSUE THREAD

**Issue by megheaiulian** [astro/nix-openwrt-imagebuilder#19]
Is it possible to use a snapshot version instead of  a release ?
It is common to do that when snapshot has important performance improvements vs the release.

**Comment by astro** [comment]
Updating the `sha256sums` daily anyway, we could add the `snapshots` "release", too.

**Comment by astro** [comment]
Can you spoil me about the details of the performance improvements in snapshot?

**Comment by megheaiulian** [comment]
This is device/arch/target specific. In the case of one such device the 5GHz WIFI is barely usable in the latest release while in snapshot release it is much better. 
E.g.: https://forum.openwrt.org/t/openwrt-on-mt7621-mt7615n-devices-with-5ghz-problems/107392
