### ISSUE TITLE
Build with flags?

### ISSUE THREAD

**Issue by austinbutler** [astro/nix-openwrt-imagebuilder#24]
I want to have `dropbear` built with `ECC` enabled. There are options for this in `make menuconfig`, but actually getting the build to succeed on NixOS seems not easy. These are the options from `make menuconfig`:

```
CONFIG_DROPBEAR_ECC=y
CONFIG_DROPBEAR_ECC_FULL=y
```

So I'm wondering if there's a way to pass that to the build or somehow override the build of `dropbear`.

**Comment by astro** [comment]
The imagebuilder doesn't recompile anything but reuses the binary packages from downloads.openwrt.org.

I would prefer a proper OpenWRT build in Nix derivations, too. Implementation attempts are encouraged!

**Comment by austinbutler** [comment]
Leaving this here as a note.

Another alternative that may work if one can build their own package and wants to put that into the image: https://forum.openwrt.org/t/custom-build-package-inside-image-builder-image/40350/13
