### ISSUE TITLE
Building from snapshot - error cached-profiles/snapshot.nix

### ISSUE THREAD

**Issue by joe2xyz** [astro/nix-openwrt-imagebuilder#37]
Hi @astro ,

Thank you very much for this project, it's fantastic!

I followed the following steps:

``` sh
git clone <this> && cd nix-openwrt-imagebuilder
nix run .#generate-hashes snapshot
nix build --override-input openwrt-imagebuilder "git+file://$(pwd)" .....
```

The .... is a directory with a flake - pretty much just your example with one change:
``` nix
profiles = openwrt-imagebuilder.lib.profiles { inherit pkgs; release = "snapshot"; };
```

But I get an error:

```
error: getting status of '/nix/store/jja09jalv7h719v3f2q0q9y6282qqxd1-source/cached-profiles/snapshot.nix': No such file or directory
```

I realized that I'm missing a file in `cached-profiles` and I decided to run:

```
nix run .#cached-profiles snapshot
```

which after long run ended up with
```
error: unable to execute '/nix/store/qfsrqgfd8zz1fch7z6pw9qsapgcvpd5a-openwrt-cached-profiles/bin/openwrt-cached-profiles': No such file or directory
```

Could you please tell how to build a snapshot?

Thank you.

**Comment by astro** [comment]
Thank you for your report!

`.#cached-profiles` is to be built with plain `nix build`

Please pull and retry.

**Comment by joe2xyz** [comment]
It is working! Thank you @astro , amazing tool!
